title: Mangena Venu Madhavan
description: Generative AI | Data Science | Agentic AI
theme: jekyll-theme-leap-day
author: Mangena Venu Madhavan
email: venumangenamadhavan@gmail.com
social_media_links:
  github: madhavan11601828
plugins:
  - jekyll-feed
  - jekyll-seo-tag
